language: objective-c 
osx_image: xcode11
cache:
  - bundler
install:
  - bundle install

jobs:
  include:
    - script: bundle exec fastlane test
      name: UnitTests
    - script: bundle exec fastlane ui_test
      name: UITests
    - script: bundle exec fastlane snapshot_test
      name: SnapshotTests
