language: objective-c 
osx_image: xcode11.2

before_install:
  - bundle install

jobs:
  include:
    - script: bundle exec fastlane test
      name: UnitTests
    - script: bundle exec fastlane screenshots_limited
      name: UITests
