Scheme = 'Critical Maps'
Screenshots_Output = 'build/screenshots' 
AppIdentifier = 'de.pokuslabs.criticalmassberlin'

skip_docs

default_platform(:ios)

platform :ios do

  desc 'Run unit tests'
  lane :test do
    scan(
      project: "CriticalMaps.xcodeproj",
      scheme: Scheme,
      device: 'iPhone 13',
      result_bundle: true,
      xcargs: '-skipPackagePluginValidation -skipMacroValidation'
    )
    trainer(path: "./fastlane/test_output", output_directory: "./fastlane")
  end
end
