# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from

if `xcrun simctl list | grep "SE"`.length > 0
  devices([
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone SE",
    "iPhone X",
    "iPhone 11 Pro Max"
  ])
else
  devices([
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone X",
    "iPhone 11 Pro Max"
  ])
end 

languages([
  "en-US",
  "de-DE",
  "fr-FR",
  "it-IT"
])
