# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone X",
  "iPhone 11 Pro Max"
])

languages([
  "en-US",
  "de-DE",
  "fr-FR",
  "it-IT"
])
