name: Format

on:
  push:
    branches:
      - main

jobs:
  swift_format:
    name: swiftformat
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Format
        run: make format

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swift-format
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}