name: Format

on:
  push:
    branches:
      - main

jobs:
  swift_format:
    name: swiftformat
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Format
        run: make format

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          token: ${{ secrets.PAT }}
          commit-message: format code
          committer: GitHub <noreply@github.com>
          branch: format-main
          delete-branch: true
          title: 'Format main'
          labels: |
            swiftformat
            automated pr
          team-reviewers: |
            owners
          draft: false